starting_message = ("and it's lights out and away we go")
starting_grid = ("starting grid")
starts_good = ('gets away well from pole and')
cant_overtake = ("can't even try to overtake him")
starts_bad = ("doesn't get away well from pole and ")
overtake_attempt1 = "Tries to overtake him"
overtake_attempt2 = "attempts to dive down the inside of"
overtake_attempt = [overtake_attempt1,overtake_attempt2]
pole_overtake = ["OH MY GOD WHAT A MOVE FROM HIM","AND HE MAKES IT!"]
overtakeFailureMsg = ["unfortnately he can't overtake him","but there is not enough space there, so he backs out"]
overtakeSuccesMsg =  ["AND HE MAKES IT!","OH MY GOD WHAT A MOVE FROM HIM","HE FINALLY HE OVERTOOK HIM"]
oh_no = ("OH NO!!!")
oh_god = "OH MY GOD!"
damn = ("damn 2 cars are involved in a incident,")
hit_by = ("has been hit by")
both_out= ("and now they are both out of the race")
impossible_move = ("WOW that was an impossible move by ")
who_tried = ("who tried to overtake")
impossible_place = ("in a impossible place, and now they are both out.")
unlucky = "how unlucky for"
taken_out = "who has been taken out from"
crash_type1 = ("destroyed")
out = "is out of the race"
retired = "retireing "
engine_fail = "due to an engine failure"
there_is = "and there he is"
barrier = "who has gone straight into the barrier"
gravel = "stuck in the gravel"
LAP = "lap "
save_report = "do you want to save the report?"
arrival_order = "final arrival order:"
podium = "podium:"
starting_grid = "here is the starting grid:"
invalid_option = "this is not a valid option insert it again"
not_saved = "report not saved"
saved = "report saved"
lapsQ ="how many laps is this race going to be?"