starting_message = ('uno, due tre, quattro, allo spegnimento il via al gran premio.')
starting_grid = ('griglia di partenza')
starts_good = ('parte bene dalla pole e')
cant_overtake = ("non riesce nemmeno ad avvicinarsi ")
starts_bad = ("Non ha uno scatto perfetto e ")
overtake_attempt2 = ("tenta il sorpasso su")
overtake_attempt1 = ("prova a superare")
overtake_attempt = "tenta il sorpasso su"
pole_overtake = ["OH MIO DIO CHE MANOVRA","WOW CHE STACCATA"]
overtakeFailureMsg = ["ma non riesce, era una manovra impossibile","ma non c'è spazio li, quindi si fa indietro"]
overtakeSuccesMsg =  ["E CI RIESCE, che sorpasso, DA PAURA! ","WOOOOW CHE SORPASSE","E FINALMENTE LO SUPERA"]
oh_no = ("OH NO!!!")
oh_god = "OH MIO DIO!"
damn = ("accidenti due macchine sono coinvolte in un incidente,")
hit_by = ("che è stato colpito da")
both_out= ("e ora sono entrambi fuori gara")
impossible_move = ("WOW, quella era una mossa impossibile da parte di")
who_tried = ("che ha provato a soprassare")
impossible_place = ("in un punto impossibile e ora sono entrambi fuori.")
unlucky = "che sfortuna per"
taken_out = "che è stato buttato fuori da"
crash_type1 = ("colpito da")
out = "è fuori dalla gara"
retired = "si sta ritirando"
engine_fail = "per un cedimento al motore"
there_is = "ed eccolo li"
barrier = "che è andato dritto nella barriera"
gravel = "bloccato nella ghiaia"
LAP = "giro"
save_report = "vuoi salvare il report della gara?"
arrival_order = "ordine di arrivo:"
podium = "podio:"
starting_grid = "ecco qui la griglia di partenza:"
invalid_option = "questa non è un opzione valida inseriscila di nuovo"
not_saved = "report non salvato"
saved = "report salvato"
lapsQ = "quanti giri sarà lunga questa gara?"